# Site settings
author: Caitlin Majewski
title: Flat Iron Course
header-img: img/home-bg.png
email: cmajewski@wesleyan.edu
copyright_name: Caitlin Majewski
description: > # this means to ignore newlines until "baseurl:"
  Blog on my coding journey throughout the Flat Iron course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Cmajewski

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
